development:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: hello_world_development
  username: dev
  password: <%= ENV["DEV_DATABASE_PASSWORD"] %>

test:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: hello_world_test
  username: dev
  password: <%= ENV["DEV_DATABASE_PASSWORD"] %>

production:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: hello_world_production
  username: dev
  password: <%= ENV["DEV_DATABASE_PASSWORD"] %>
